#!/usr/bin/env python3
"""
Build every table the thesis needs, as CSV and as LaTeX.

The tables are generated from the stored run records, never typed by
hand, so a number in the document is always the number the code produced.
Each emitted .tex carries a comment naming the block and the commit it
came from, which is how a table in Chapter 6 stays traceable to the run
that made it.

Two conventions run through all of it.

Both AUC forms, always. The raw integral is kept for continuity with the
preliminary results (the 240.65 in the current abstract), and the
normalised value is printed beside it because the board asked for a
number a reader can interpret without knowing the budget.

Uncertainty is never dropped. Every mean carries its standard deviation
across seeds, and the primary tables carry the bootstrap interval too. A
bare mean over five seeds is not a result.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.aggregate import aggregate_block, build_dataframe, load_records, run_statistics
from src.campaign import expand_blocks, load_campaign

PRETTY = {
    "random": "Random",
    "deterministic": "Deterministic",
    "bald_only": "BALD-only",
    "bald_diversity": "BALD + Diversity",
    "mc_dropout": "MC Dropout",
    "deep_ensemble": "Deep Ensemble (5)",
    "conformal": "Conformal",
    "swag": "SWAG",
    "bsb": "BSB",
    "psb": "PSB",
    "bsb_diversity": "BSB + Diversity",
}


def pretty(name) -> str:
    return PRETTY.get(str(name), str(name))


# ---------------------------------------------------------------------------
# LaTeX emission
# ---------------------------------------------------------------------------

def to_latex(
    df: pd.DataFrame,
    caption: str,
    label: str,
    column_format: Optional[str] = None,
    note: Optional[str] = None,
    float_format: str = "%.3f",
) -> str:
    if df.empty:
        body = "\\multicolumn{1}{c}{\\emph{no completed runs for this condition}} \\\\"
        return (
            f"% auto-generated; no data yet\n"
            f"\\begin{{table}}[ht]\n\\centering\n\\caption{{{caption}}}\n"
            f"\\label{{{label}}}\n\\begin{{tabular}}{{l}}\n\\toprule\n{body}\n"
            f"\\bottomrule\n\\end{{tabular}}\n\\end{{table}}\n"
        )

    fmt = column_format or "l" + "r" * (len(df.columns) - 1)
    latex = df.to_latex(
        index=False,
        escape=False,
        float_format=lambda v: float_format % v if pd.notnull(v) else "--",
        column_format=fmt,
        na_rep="--",
    )
    latex = latex.replace("\\toprule", "\\toprule").replace("_", "\\_")
    out = [
        "% Auto-generated by scripts/make_tables.py -- do not edit by hand.",
        "\\begin{table}[ht]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\resizebox{\\textwidth}{!}{%",
        latex.strip(),
        "}",
    ]
    if note:
        out.append(f"\\vspace{{2pt}}\n\\begin{{minipage}}{{\\textwidth}}\\footnotesize {note}\\end{{minipage}}")
    out.append("\\end{table}")
    return "\n".join(out) + "\n"


def _pm(agg: Dict, key: str, fmt: str = "{:.3f}") -> str:
    mean = agg.get(f"{key}_mean")
    std = agg.get(f"{key}_std")
    if mean is None or (isinstance(mean, float) and np.isnan(mean)):
        return "--"
    if std is None:
        return fmt.format(mean)
    return f"{fmt.format(mean)} $\\pm$ {fmt.format(std)}"


def _ci(agg: Dict, key: str, fmt: str = "{:.3f}") -> str:
    lo, hi = agg.get(f"{key}_ci_low"), agg.get(f"{key}_ci_high")
    if lo is None or hi is None:
        return "--"
    return f"[{fmt.format(lo)}, {fmt.format(hi)}]"


def _write(out_dir: Path, name: str, df: pd.DataFrame, latex: str) -> List[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    csv_path = out_dir / f"{name}.csv"
    tex_path = out_dir / f"{name}.tex"
    df.to_csv(csv_path, index=False, float_format="%.4f")
    tex_path.write_text(latex)
    return [csv_path, tex_path]


# ---------------------------------------------------------------------------
# Individual tables
# ---------------------------------------------------------------------------

def table_main_grid(aggs: List[Dict], out_dir: Path) -> List[Path]:
    """H1/H3: strategy x L0 x budget, with both AUC forms."""
    rows = []
    for agg in sorted(
        aggs, key=lambda a: (str(a.get("dataset")), a.get("l0_size") or 0,
                             a.get("budget") or 0, str(a.get("strategy")))
    ):
        rows.append(
            {
                "Dataset": agg.get("dataset", "--"),
                "$L_0$": agg.get("l0_size"),
                "$B$": agg.get("budget"),
                "Strategy": pretty(agg.get("strategy")),
                "$n$": agg.get("n_seeds"),
                "AUC$_{norm}$ $\\uparrow$": _pm(agg, "auc_normalized"),
                "95\\% CI": _ci(agg, "auc_normalized"),
                "AUC$_{raw}$": _pm(agg, "auc", "{:.1f}"),
                "mAP@50 $\\uparrow$": _pm(agg, "final_mAP50"),
                "Recall $\\uparrow$": _pm(agg, "final_recall"),
                "Precision $\\uparrow$": _pm(agg, "final_precision"),
            }
        )
    df = pd.DataFrame(rows)
    latex = to_latex(
        df,
        caption=(
            "Annotation efficiency across acquisition strategies, initial "
            "labelled set sizes $L_0$ and annotation budgets $B$ "
            "(mean $\\pm$ std over $n$ seeds). AUC$_{norm}$ is the area under "
            "the mAP@50 learning curve divided by the annotation budget, so it "
            "reads as mean detection quality per unit of annotation and is "
            "comparable across budgets; AUC$_{raw}$ is the unnormalised "
            "integral of Equation~5.1, reported for continuity with the "
            "preliminary results."
        ),
        label="tab:main_grid",
        note=(
            "Bootstrap confidence intervals use $n=1000$ resamples at "
            "$\\alpha=0.05$, resampling seeds."
        ),
    )
    return _write(out_dir, "main_grid", df, latex)


def table_sweet_spot(aggs: List[Dict], out_dir: Path) -> List[Path]:
    """Where the proposed strategy's advantage over random is largest."""
    by_cell: Dict[tuple, Dict[str, Dict]] = {}
    for agg in aggs:
        key = (agg.get("dataset"), agg.get("l0_size"), agg.get("budget"))
        by_cell.setdefault(key, {})[str(agg.get("strategy"))] = agg

    rows = []
    for (dataset, l0, budget), strategies in sorted(
        by_cell.items(), key=lambda kv: (str(kv[0][0]), kv[0][1] or 0, kv[0][2] or 0)
    ):
        proposed = strategies.get("bald_diversity")
        baseline = strategies.get("random")
        if not proposed or not baseline:
            continue
        p_auc = proposed.get("auc_normalized_mean")
        b_auc = baseline.get("auc_normalized_mean")
        if p_auc is None or b_auc is None:
            continue
        gain = p_auc - b_auc
        rel = (gain / b_auc * 100) if b_auc else np.nan
        rows.append(
            {
                "Dataset": dataset,
                "$L_0$": l0,
                "$B$": budget,
                "Random": f"{b_auc:.3f}",
                "BALD+Div": f"{p_auc:.3f}",
                "Gain": f"{gain:+.3f}",
                "Gain (\\%)": f"{rel:+.1f}",
                "Recall gain": f"{(proposed.get('final_recall_mean') or 0) - (baseline.get('final_recall_mean') or 0):+.3f}",
            }
        )

    df = pd.DataFrame(rows)
    if not df.empty:
        df = df.sort_values("Gain", ascending=False)
    latex = to_latex(
        df,
        caption=(
            "Sweet-spot search: advantage of the proposed BALD + Diversity "
            "strategy over random sampling in normalised AUC, by initial "
            "labelled set size $L_0$ and annotation budget $B$. Rows are "
            "ordered by absolute gain, so the operating point where informed "
            "selection pays off most is the first row."
        ),
        label="tab:sweet_spot",
        note=(
            "A gain that shrinks as $L_0$ grows is the expected pattern: once "
            "the initial set already covers the class distribution, the choice "
            "of which frames to annotate next matters less."
        ),
    )
    return _write(out_dir, "sweet_spot", df, latex)


def table_shift(aggs: List[Dict], baseline_aggs: List[Dict], out_dir: Path) -> List[Path]:
    """H2: stability and recovery under covariate shift."""
    baselines = {}
    for agg in baseline_aggs:
        baselines[agg.get("pair_label")] = agg

    rows = []
    for agg in sorted(
        aggs, key=lambda a: (str(a.get("pair_label")), str(a.get("strategy")))
    ):
        pair = agg.get("pair_label")
        base = baselines.get(pair, {})
        base_recall = base.get("baseline_target_recall_mean")
        final_recall = agg.get("final_recall_mean")
        recovery = (
            f"{final_recall - base_recall:+.3f}"
            if base_recall is not None and final_recall is not None
            else "--"
        )
        rows.append(
            {
                "Shift pair": str(pair).replace("_to_", " $\\rightarrow$ "),
                "Strategy": pretty(agg.get("strategy")),
                "$n$": agg.get("n_seeds"),
                # `is not None`, not truthiness: a baseline recall of
                # exactly 0.0 is a real and important measurement (the
                # source model finding nothing at all on the target
                # domain), and must not render as missing data.
                "Recall (no adapt.)": (
                    f"{base_recall:.3f}" if base_recall is not None else "--"
                ),
                "Recall (adapted) $\\uparrow$": _pm(agg, "final_recall"),
                "Recovery": recovery,
                "mAP@50 $\\uparrow$": _pm(agg, "final_mAP50"),
                "Recall var. $\\downarrow$": _pm(agg, "recall_variance", "{:.4f}"),
                "Monotonicity $\\uparrow$": _pm(agg, "recall_monotonicity", "{:.2f}"),
                "AUC$_{norm}$ $\\uparrow$": _pm(agg, "auc_normalized"),
            }
        )
    df = pd.DataFrame(rows)
    latex = to_latex(
        df,
        caption=(
            "Hypothesis H2 under real cross-dataset covariate shift. "
            "\\emph{Recall (no adapt.)} is the source-trained model evaluated "
            "on the target domain without adaptation, which is the zero point "
            "for the \\emph{Recovery} column. Recall variance is the "
            "inter-cycle variance of recall: lower means a more stable "
            "learning trajectory, which is the criterion H2 is stated in."
        ),
        label="tab:shift_h2",
        note=(
            "A Bayesian estimator satisfies H2 if it lowers recall variance "
            "relative to the deterministic estimator at comparable final "
            "recall; a variance reduction bought with a recall loss does not."
        ),
    )
    return _write(out_dir, "shift_h2", df, latex)


def table_uncertainty_methods(aggs: List[Dict], out_dir: Path) -> List[Path]:
    """Accuracy and cost of each uncertainty estimator."""
    rows = []
    for agg in sorted(aggs, key=lambda a: -(a.get("auc_normalized_mean") or 0)):
        rows.append(
            {
                "Method": pretty(agg.get("method") or agg.get("strategy")),
                "$n$": agg.get("n_seeds"),
                "AUC$_{norm}$ $\\uparrow$": _pm(agg, "auc_normalized"),
                "mAP@50 $\\uparrow$": _pm(agg, "final_mAP50"),
                "Recall $\\uparrow$": _pm(agg, "final_recall"),
                "Recall var. $\\downarrow$": _pm(agg, "recall_variance", "{:.4f}"),
                "Acq. overhead $\\times$ $\\downarrow$": _pm(agg, "mc_overhead_ratio", "{:.1f}"),
                "Deploy latency (ms)": _pm(agg, "latency_ms_mean", "{:.2f}"),
            }
        )
    df = pd.DataFrame(rows)
    latex = to_latex(
        df,
        caption=(
            "Comparison of approximate uncertainty estimators under an "
            "identical pipeline, splits and seeds. \\emph{Acq. overhead} is "
            "the cost of scoring one candidate relative to a single "
            "deterministic forward pass, and is the figure that decides "
            "whether a method is affordable during a mission; deployment "
            "latency is unaffected because uncertainty estimation runs off "
            "the real-time path."
        ),
        label="tab:uncertainty_methods",
        note=(
            "Deep Ensembles additionally require $M$ sets of weights in "
            "storage and $M$ full training runs, a cost not visible in the "
            "per-candidate overhead column."
        ),
    )
    return _write(out_dir, "uncertainty_methods", df, latex)


def table_profiling(aggs: List[Dict], out_dir: Path) -> List[Path]:
    """H4: the four resources the board asked for."""
    rows = []
    for agg in aggs:
        platform = "--"
        rows.append(
            {
                "Strategy": pretty(agg.get("strategy")),
                "Latency mean (ms)": _pm(agg, "latency_ms_mean", "{:.2f}"),
                "p95 (ms)": _pm(agg, "latency_ms_p95", "{:.2f}"),
                "p99 (ms)": _pm(agg, "latency_ms_p99", "{:.2f}"),
                "FPS": _pm(agg, "throughput_fps", "{:.1f}"),
                "Over budget (\\%)": _pm(agg, "frames_over_budget_pct", "{:.2f}"),
                "Peak RAM (MB)": _pm(agg, "peak_host_memory_mb", "{:.0f}"),
                "Peak VRAM (MB)": _pm(agg, "peak_gpu_memory_mb", "{:.0f}"),
                "CPU (\\%)": _pm(agg, "cpu_util_pct_mean", "{:.1f}"),
                "GPU (\\%)": _pm(agg, "gpu_util_pct_mean", "{:.1f}"),
                "Power (W)": _pm(agg, "gpu_power_w_mean", "{:.1f}"),
                "Energy/cycle (J)": _pm(agg, "gpu_energy_j_per_cycle", "{:.0f}"),
                "Fine-tune (s/cycle)": _pm(agg, "finetune_s_per_cycle", "{:.1f}"),
                "Network (MB/cycle)": _pm(agg, "network_mb_per_cycle", "{:.1f}"),
            }
        )
    df = pd.DataFrame(rows)
    latex = to_latex(
        df,
        caption=(
            "Hypothesis H4: operational cost of continuous adaptation. "
            "Latency percentiles describe the deployed deterministic forward "
            "pass against the 33\\,ms real-time budget; memory, utilisation, "
            "power and energy are sampled during the fine-tuning phase, which "
            "is the peak-demand window of the cycle. Network traffic counts "
            "the payload the closed loop must move per cycle: candidate frames "
            "uplinked for annotation, labels returned, and the updated weights "
            "redistributed."
        ),
        label="tab:h4_profiling",
        note=(
            "All figures in this table were measured on the platform recorded "
            "in the corresponding run records. Embedded-hardware figures must "
            "be obtained by executing the same block on the target device; "
            "workstation measurements bound the embedded case from below and "
            "are not a substitute for it."
        ),
    )
    return _write(out_dir, "h4_profiling", df, latex)


def table_diversity(aggs: List[Dict], out_dir: Path) -> List[Path]:
    """H3/C4: direct evidence about the selection mechanism."""
    rows = []
    for agg in aggs:
        # Aggregation appends `_mean` to every run-level scalar, so the
        # per-run key `diversity_coverage_mean` becomes
        # `diversity_coverage_mean_mean` here. Checking the un-suffixed
        # name silently emptied this table.
        if agg.get("diversity_coverage_mean_mean") is None:
            continue
        rows.append(
            {
                "$L_0$": agg.get("l0_size"),
                "$B$": agg.get("budget"),
                "Strategy": pretty(agg.get("strategy")),
                "Cluster coverage $\\uparrow$": _pm(agg, "diversity_coverage_mean"),
                "Selection entropy $\\uparrow$": _pm(agg, "diversity_selection_entropy_mean"),
                "Redundancy rate $\\downarrow$": _pm(agg, "diversity_redundancy_rate_mean"),
                "AUC$_{norm}$": _pm(agg, "auc_normalized"),
            }
        )
    df = pd.DataFrame(rows)
    latex = to_latex(
        df,
        caption=(
            "Diversity diagnostics of the acquisition step, measured on the "
            "selected batches themselves rather than inferred from downstream "
            "accuracy. Cluster coverage is the fraction of $k$-means clusters "
            "in the candidate pool that receive at least one annotation per "
            "cycle; redundancy rate is the fraction of selected pairs closer "
            "in embedding space than the 5th percentile of the pool's own "
            "distance distribution, which is the near-duplicate frame problem "
            "that diversity-aware selection exists to prevent."
        ),
        label="tab:diversity",
        note=(
            "These columns separate the mechanism from its effect: they show "
            "whether selection is actually more spread out, independently of "
            "whether that spreading improved mAP@50."
        ),
    )
    return _write(out_dir, "diversity", df, latex)


def table_forgetting(aggs: List[Dict], out_dir: Path) -> List[Path]:
    """Continual-learning behaviour over a long horizon."""
    rows = []
    for agg in aggs:
        if agg.get("backward_transfer_mean") is None:
            continue
        rows.append(
            {
                "Strategy": pretty(agg.get("strategy")),
                "Cycles": agg.get("cycles"),
                "$n$": agg.get("n_seeds"),
                "BWT": _pm(agg, "backward_transfer"),
                "Forgetting $\\downarrow$": _pm(agg, "forgetting_measure"),
                "Retention (prior) $\\uparrow$": _pm(agg, "retention_mean_prior_domains"),
                "Source retention $\\uparrow$": _pm(agg, "source_retention"),
                "Stability gap $\\downarrow$": _pm(agg, "stability_gap"),
                "Plasticity $\\uparrow$": _pm(agg, "plasticity"),
            }
        )
    df = pd.DataFrame(rows)
    latex = to_latex(
        df,
        caption=(
            "Catastrophic forgetting over a long adaptation horizon. Backward "
            "transfer (BWT) is the mean change on previously seen domains from "
            "first to last evaluation; the forgetting measure is the mean drop "
            "from each domain's peak, which -- unlike BWT -- cannot be masked "
            "by a domain that improved. Plasticity is the gain on the domain "
            "being adapted to, reported alongside so the stability-plasticity "
            "trade-off is visible rather than argued."
        ),
        label="tab:forgetting",
        note=(
            "Operationally, \\emph{source retention} answers the question that "
            "matters most: whether a detector adapted to a new disaster scene "
            "still finds what it was originally trained to find."
        ),
    )
    return _write(out_dir, "forgetting", df, latex)


def table_sensitivity(aggs: List[Dict], out_dir: Path) -> List[Path]:
    """One-factor-at-a-time hyperparameter sensitivity."""
    rows = []
    for agg in sorted(
        aggs, key=lambda a: (str(a.get("sweep_param")), str(a.get("sweep_value")))
    ):
        if not agg.get("sweep_param"):
            continue
        rows.append(
            {
                "Parameter": str(agg.get("sweep_param")).replace("_", " "),
                "Value": agg.get("sweep_value"),
                "$n$": agg.get("n_seeds"),
                "AUC$_{norm}$ $\\uparrow$": _pm(agg, "auc_normalized"),
                "mAP@50": _pm(agg, "final_mAP50"),
                "Recall": _pm(agg, "final_recall"),
                "Acq. time (s/cycle)": _pm(agg, "mc_overhead_ratio", "{:.2f}"),
                "Latency (ms)": _pm(agg, "latency_ms_mean", "{:.2f}"),
            }
        )
    df = pd.DataFrame(rows)
    latex = to_latex(
        df,
        caption=(
            "Hyperparameter sensitivity at $L_0 = 100$, varying one parameter "
            "at a time around the baseline configuration. The comparison of "
            "interest is not the best cell but the spread within each "
            "parameter: a parameter whose rows differ by less than the seed "
            "standard deviation is one the results do not depend on, and can "
            "be fixed by argument rather than by tuning."
        ),
        label="tab:sensitivity",
        note=(
            "One-factor-at-a-time by design: a full factorial over these four "
            "parameters is 144 cells before replication. Interaction effects "
            "are therefore out of scope and are declared as such."
        ),
    )
    return _write(out_dir, "sensitivity", df, latex)


def table_statistics(rows: List[Dict], out_dir: Path) -> List[Path]:
    """Significance tests with multiplicity correction."""
    df = pd.DataFrame(rows)
    if not df.empty:
        display = pd.DataFrame(
            {
                "Context": df["context"],
                "Metric": df["metric"].str.replace("_", " "),
                "Comparison": df["comparison"].map(
                    lambda s: " vs ".join(pretty(p.strip()) for p in s.split(" vs "))
                ),
                "$\\Delta$": df["difference"].map(lambda v: f"{v:+.4f}"),
                "95\\% CI": df.apply(
                    lambda r: f"[{r['ci_low']:.4f}, {r['ci_high']:.4f}]", axis=1
                ),
                "$p$": df["p_value"].map(lambda v: f"{v:.4f}" if pd.notnull(v) else "--"),
                "$p_{Holm}$": df["p_holm"].map(
                    lambda v: f"{v:.4f}" if pd.notnull(v) else "--"
                ),
                "Sig.": df["significant"].map(lambda b: "yes" if b else "no"),
                "$\\delta$": df["cliffs_delta"].map(lambda v: f"{v:+.2f}"),
                "Effect": df["effect"],
            }
        )
    else:
        display = df
    latex = to_latex(
        display,
        caption=(
            "Paired statistical comparisons within each experimental context. "
            "Differences are tested with the exact Wilcoxon signed-rank test on "
            "seed-paired values, corrected across comparisons with the "
            "Holm-Bonferroni procedure; confidence intervals come from 1000 "
            "bootstrap resamples of the seed pairing."
        ),
        label="tab:significance",
        note=(
            "With five seeds the smallest attainable two-sided $p$ is 0.0625, "
            "so a large Cliff's $\\delta$ accompanied by a non-significant $p$ "
            "should be read as an underpowered comparison rather than as "
            "evidence of no difference."
        ),
    )
    return _write(out_dir, "significance", df, latex)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def build_all_tables(spec, results_root: str = "results", out_dir: Path = Path("tables")) -> List[Path]:
    out_dir = Path(out_dir)
    written: List[Path] = []

    expected: Dict[str, int] = {}
    for block in spec.blocks:
        expected[block["id"]] = int(block.get("n_seeds", spec.n_seeds))

    aggregates: Dict[str, List[Dict]] = {}
    for block in spec.blocks:
        block_id = block["id"]
        records = load_records(results_root, block_id)
        if not records:
            continue
        aggregates[block_id] = aggregate_block(
            records, n_expected_per_condition=expected.get(block_id)
        )

    reporting = spec.reporting or {}
    stats_cfg = reporting.get("statistics", {})

    builders = [
        ("E1_main_grid", table_main_grid),
        ("E1_main_grid", table_sweet_spot),
        ("E1_main_grid", table_diversity),
        ("E3_uncertainty_methods", table_uncertainty_methods),
        ("E6_operational_profiling", table_profiling),
        ("E5_long_horizon", table_forgetting),
        ("E4_sensitivity", table_sensitivity),
    ]
    for block_id, builder in builders:
        aggs = aggregates.get(block_id)
        if not aggs:
            continue
        try:
            written.extend(builder(aggs, out_dir))
        except Exception as exc:
            print(f"[tables] {builder.__name__} failed for {block_id}: {exc}")

    shift_aggs = aggregates.get("E2b_shift_real", [])
    baseline_aggs = aggregates.get("E2a_shift_baseline", [])
    if shift_aggs or baseline_aggs:
        written.extend(table_shift(shift_aggs, baseline_aggs, out_dir))

    intensity_aggs = aggregates.get("E2c_shift_intensity", [])
    if intensity_aggs:
        written.extend(table_shift(intensity_aggs, [], out_dir / "intensity"))

    # Statistics across every block that has replicated conditions.
    all_stats: List[Dict] = []
    for block_id, aggs in aggregates.items():
        try:
            all_stats.extend(
                run_statistics(
                    aggs,
                    metrics=stats_cfg.get(
                        "primary_metrics",
                        ["auc_normalized", "final_recall", "final_mAP50", "recall_variance"],
                    ),
                    reference=stats_cfg.get("reference_strategy", "bald_diversity"),
                    n_bootstrap=int(stats_cfg.get("n_bootstrap", 1000)),
                    alpha=float(stats_cfg.get("alpha", 0.05)),
                )
            )
        except Exception as exc:
            print(f"[tables] statistics failed for {block_id}: {exc}")
    if all_stats:
        written.extend(table_statistics(all_stats, out_dir))

    # A single wide CSV of every aggregate, for ad-hoc inspection.
    flat = [a for aggs in aggregates.values() for a in aggs]
    if flat:
        out_dir.mkdir(parents=True, exist_ok=True)
        df = build_dataframe(flat)
        path = out_dir / "all_aggregates.csv"
        df.to_csv(path, index=False, float_format="%.6f")
        written.append(path)

    return written


def main() -> int:
    import argparse

    parser = argparse.ArgumentParser(description="Generate thesis tables")
    parser.add_argument("--config", default="configs/campaign.yaml")
    parser.add_argument("--results", default="results")
    parser.add_argument("--out", default="tables")
    args = parser.parse_args()

    spec = load_campaign(args.config)
    written = build_all_tables(spec, results_root=args.results, out_dir=Path(args.out))
    for path in written:
        print(f"  {path}")
    print(f"\n{len(written)} file(s) written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
